# Generated by Django 5.1.4 on 2025-03-22 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('content_type', models.CharField(choices=[('headline', 'Заголовок'), ('creative', 'Креатив (заголовок+описание)'), ('offer', 'Оффер'), ('pain_gain', 'УТП / боль / выгода'), ('ab_test', 'Идея для A/B теста')], default='headline', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ctr', models.FloatField(default=0.0)),
                ('epc', models.FloatField(default=0.0)),
                ('cr', models.FloatField(default=0.0)),
                ('revenue', models.FloatField(default=0.0)),
                ('views', models.IntegerField(default=0)),
                ('leads', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('spend', models.FloatField(default=0.0)),
                ('success_score', models.FloatField(default=0.0)),
                ('is_successful', models.BooleanField(default=False)),
            ],
        ),
    ]
