# Generated by Django 5.1.4 on 2025-06-08 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignvariant',
            name='approvals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignvariant',
            name='leads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignvariant',
            name='payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='TrafficPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='campaigns.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'name')},
            },
        ),
    ]
